# kind: StorageClass
# apiVersion: storage.k8s.io/v1beta1
# metadata:
#   name: standard
# provisioner: kubernetes.io/aws-ebs
# parameters:
#   type: gp2
#   zone: eu-west-1a

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-volume
provisioner: docker.io/hostpath
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
